#![no_std]
#![no_main]

use core::mem;

use crate::ble_dfu::BleDfu;
use defmt::unwrap;
use embassy_executor::Spawner;
use embassy_time::Timer;

use {defmt_rtt as _, panic_probe as _};

use embassy_nrf::gpio::{Level, Output, OutputDrive};
use embassy_nrf::interrupt::Priority;
use embassy_nrf::wdt::{self, Watchdog, WatchdogHandle};
use nrf_softdevice::{
    Flash, Softdevice,
    ble::{advertisement_builder::ServiceList, gatt_server},
    raw,
};

mod ble_dfu;
use ble_dfu::FirmwareService;
use ble_dfu::FirmwareServiceEvent;

#[nrf_softdevice::gatt_server]
struct Server {
    firmware_service: FirmwareService,
}

#[embassy_executor::task]
async fn softdevice_task(sd: &'static Softdevice) -> ! {
    sd.run().await
}

#[embassy_executor::main]
async fn main(spawner: Spawner) {
    defmt::info!("Starting");

    let mut config = embassy_nrf::config::Config::default();
    config.gpiote_interrupt_priority = Priority::P2;
    config.time_interrupt_priority = Priority::P2;

    let p = embassy_nrf::init(config);

    defmt::info!("Embassy initialized");

    // softdevice init
    let config = nrf_softdevice::Config {
        clock: Some(raw::nrf_clock_lf_cfg_t {
            source: raw::NRF_CLOCK_LF_SRC_RC as u8,
            rc_ctiv: 16,
            rc_temp_ctiv: 2,
            accuracy: raw::NRF_CLOCK_LF_ACCURACY_500_PPM as u8,
        }),
        conn_gap: Some(raw::ble_gap_conn_cfg_t {
            conn_count: 6,
            event_length: 24,
        }),
        conn_gatt: Some(raw::ble_gatt_conn_cfg_t { att_mtu: 512 }),
        gatts_attr_tab_size: Some(raw::ble_gatts_cfg_attr_tab_size_t {
            attr_tab_size: raw::BLE_GATTS_ATTR_TAB_SIZE_DEFAULT,
        }),
        gap_role_count: Some(raw::ble_gap_cfg_role_count_t {
            adv_set_count: 1,
            periph_role_count: 3,
            central_role_count: 3,
            central_sec_count: 0,
            _bitfield_1: raw::ble_gap_cfg_role_count_t::new_bitfield_1(0),
        }),
        gap_device_name: Some(raw::ble_gap_cfg_device_name_t {
            p_value: b"HelloRust" as *const u8 as _,
            current_len: 9,
            max_len: 9,
            write_perm: unsafe { mem::zeroed() },
            _bitfield_1: raw::ble_gap_cfg_device_name_t::new_bitfield_1(
                raw::BLE_GATTS_VLOC_STACK as u8,
            ),
        }),
        ..Default::default()
    };

    let sd = Softdevice::enable(&config);
    let ble_server = unwrap!(Server::new(sd));
    spawner.spawn(unwrap!(softdevice_task(sd)));

    defmt::info!("Softdevice initialized");

    let mut led = Output::new(p.P0_13, Level::Low, OutputDrive::Standard);

    let wdt = p.WDT;
    let wdt_config = wdt::Config::try_new(&wdt).unwrap();
    let (_wdt, [mut wdt_handle]) = match Watchdog::try_new(wdt, wdt_config) {
        Ok(x) => x,
        Err(_) => {
            // Watchdog already active with the wrong number of handles, waiting for it to timeout...
            loop {
                cortex_m::asm::wfe();
            }
        }
    };

    defmt::info!("Watchdog initialized");

    // spawner.spawn(unwrap!(blink_and_pet(led, wdt_handle)));
    spawner.spawn(unwrap!(ble_server_task(sd, ble_server)));

    loop {
        wdt_handle.pet();
        led.set_high();
        Timer::after_millis(100).await;
        led.set_low();
        Timer::after_millis(100).await;
    }
}

#[embassy_executor::task]
async fn ble_server_task(sd: &'static Softdevice, server: Server) {
    use embassy_futures::select::{Either, select};
    use embassy_sync::blocking_mutex::raw::NoopRawMutex;
    use embassy_sync::channel::Channel;
    use nrf_softdevice::ble::advertisement_builder::{
        Flag, LegacyAdvertisementBuilder, LegacyAdvertisementPayload,
    };
    use nrf_softdevice::ble::peripheral;

    let mut config = peripheral::Config::default();
    config.interval = 50;

    static ADV_DATA: LegacyAdvertisementPayload = LegacyAdvertisementBuilder::new()
        .flags(&[Flag::GeneralDiscovery, Flag::LE_Only])
        .short_name("BLE DFU")
        .build();

    static SCAN_DATA: LegacyAdvertisementPayload = LegacyAdvertisementBuilder::new()
        .services_128(
            ServiceList::Incomplete,
            &[0x00001000_b0cd_11ec_871f_d45ddf138840_u128.to_le_bytes()],
        )
        .build();

    let adv = peripheral::ConnectableAdvertisement::ScannableUndirected {
        adv_data: &ADV_DATA,
        scan_data: &SCAN_DATA,
    };

    let ble_dfu = BleDfu::new(sd).await;

    loop {
        let conn = unwrap!(peripheral::advertise_connectable(sd, adv, &config).await);

        defmt::info!("BLE connected");

        let channel: Channel<NoopRawMutex, FirmwareServiceEvent, 4> = Channel::new();

        // Run the GATT server on the connection. This returns when the connection gets disconnected.
        //
        // Event enums (ServerEvent's) are generated by nrf_softdevice::gatt_server
        // proc macro when applied to the Server struct above
        let gatt_future = gatt_server::run(&conn, &server, |e| match e {
            ServerEvent::FirmwareService(e) => {
                if let Err(e) = channel.try_send(e) {
                    defmt::error!("Try send error");
                }
            }
        });

        let handler_future = async {
            loop {
                let event = channel.receive().await;
                ble_dfu.handle_event(event).await;
            }
        };

        let e = match select(gatt_future, handler_future).await {
            Either::First(e) => e, // gatt_server disconnected
            Either::Second(_) => unreachable!(),
        };

        // Log the actual disconnect reason
        if let Some(reason) = conn.disconnect_reason() {
            defmt::info!("gatt_server disconnected, reason: {:?}", reason);
        } else {
            defmt::info!("gatt_server disconnected, reason unknown");
        }

        defmt::info!("gatt_server run exited with error: {:?}", e);

        // Connection dropped — finalize DFU if it was requested.
        // This runs outside select so flash writes can't be cancelled.
        ble_dfu.finalize_if_pending().await;
    }
}

#[embassy_executor::task]
async fn blink_and_pet(mut led: Output<'static>, mut wdt_handle: WatchdogHandle) -> ! {
    loop {
        wdt_handle.pet();
        led.set_high();
        Timer::after_millis(100).await;
        led.set_low();
        Timer::after_millis(100).await;
    }
}
